[package]
name = "wurstdoktor"
version = "0.1.0"
authors = ["Blake"]
edition = "2018"

[dependencies]
failure      = "0.1.5"
pom          = "3.0.1"
serde        = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_yaml   = "0.8"
structopt    = "0.2"
